baseurl: /bootstrap-boilerplate

sass:
  sass_dir: assets/bootstrap/scss

collections:
  things:
    sort_by: order
    output: true

plugins:
  - jekyll-get-json

jekyll_get_json:
  - data: tokens
    json: 'https://v1.nocodeapi.com/pglevy/airtable/LDTzULYnuAgBNkGH?tableName=tokens'
